### ISSUE TITLE
docker run with -t

### ISSUE THREAD

**Issue by carmineyiu** [spujadas/lighttpd-docker#12]
when i change docker run -d to -t in your README, the command prompt does not run. does it -it and add sh if I want to return an command prompt for login to container?

**Comment by spujadas** [comment]
Yes, if you start a container like this:

    docker run --rm -d -t -v $(pwd):/var/www/localhost/htdocs -p 80:80 sebp/lighttpd

Then you can get a shell prompt in the container like this:

    docker exec -it <container-name> /bin/sh

(Closing as not actually an issue with the image, but feel free to comment if unclear.)
