### ISSUE TITLE
403 forbidden for php files

### ISSUE THREAD

**Issue by soydepr** [spujadas/lighttpd-docker#14]
i have enable the following mods 
    "mod_rewrite",
    "mod_redirect",

    "mod_access",
    "mod_setenv",
instALLED PHP
HP 7.3.15 (cli) (built: Feb 26 2020 22:04:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies

my phpinfo() files is on localhost in /opt/lighttpd a nd i am now getting 403 forbidden

**Comment by spujadas** [comment]
This request appears to ask for help setting up and using lighttpd or its mods.
As this issue tracker is for issues with the Docker image itself, please seek guidance from support groups that can help with lighttpd (e.g. https://redmine.lighttpd.net/projects/lighttpd/boards, StackOverflow).

Closing this issue on this basis, but if you believe that this *is* an issue with the image, then please provide a detailed set of steps to reproduce your issue.

**Comment by soydepr** [comment]
fair enough
