### ISSUE TITLE
Feature request - the ability to add plugins

### ISSUE THREAD

**Issue by larssb** [spujadas/lighttpd-docker#16]
Thank you for this image.

Are there any plans on providing the ability to add plugins to this image? I have several plugins I use with my lighttpd.

Thank you.

**Comment by spujadas** [comment]
I won't be adding plugins to the image, which will remain as basic as possible to keep it lightweight 
whilst remaining extensible to suit users' needs.
If the plugins you're after are available for Alpine Linux (which the image is based on to make it as lightweight as possible), then extending the base image to install and configure these plugins is very straightforward using basic Docker features.
