### ISSUE TITLE
Image description still says 1.4.54 rather than 1.4.55

### ISSUE THREAD

**Issue by hartwork** [spujadas/lighttpd-docker#18]
Hi! The description at https://hub.docker.com/r/sebp/lighttpd still reads `lighttpd is a secure, fast, compliant, and flexible web server (lighttpd/1.4.54-r0)` i.e. the version `1.4.54-r0` has not been updated.

**Comment by spujadas** [comment]
Indeed! Forgot to change it (have to do it manually), but more to the point I forgot to remove it altogether, as several versions are actually available.
Anyway, I've just removed the version number.
