### ISSUE TITLE
ARM Builds missing

### ISSUE THREAD

**Issue by KN4CK3R** [spujadas/lighttpd-docker#20]
Hi,

after the latest build there are only amd64 builds available. All other systems are missing. I don't know whats the problem but maybe the Docker Workflow overwrites the Github Workflow results?

**Comment by spujadas** [comment]
Indeed! I've disabled Docker Hub's automated builds and re-built the images from GitHub Actions with the proper tags.
All the images seem to have been built properly.

**Comment by KN4CK3R** [comment]
Great thank you!
