### ISSUE TITLE
Are the default config files in the git repo still accurate?

### ISSUE THREAD

**Issue by pcm1ke** [spujadas/lighttpd-docker#25]
Are the default config files in the git repo still accurate? They haven't been updated in years and the values also don't seem to match the documentation at redmine.lighttpd.net. I'd like to use this image with custom config files but I'm thrown off on if I can simply use lighttpd's documentation to create my config files or if I should be using the years out of date config files in this git repo as the first step to craft my own custom config.

**Comment by spujadas** [comment]
> Are the default config files in the git repo still accurate?

Probably/possibly not, but they’re the ones packaged with the Alpine Linux lighttpd package.

> I'd like to use this image with custom config files but I'm thrown off on if I can simply use lighttpd's documentation to create my config files

^ This, definitely. The version of lighttpd in the image is the one mentioned in the image documentation, so it will work per lighttpd’s documentation.
