### ISSUE TITLE
What is example for redirect call?

### ISSUE THREAD

**Issue by alnhk** [spujadas/lighttpd-docker#3]
HI, 
I have one virtualhost running on lighthttp (LDAP based), but i want to add another virtualhost in existing http.conf where i want to redirect to one url (using existing and same port). 

please share.

**Comment by spujadas** [comment]
For help with the configuration of lighttpd please head over to http://redmine.lighttpd.net/projects/lighttpd/boards.
Closing as this is not an issue with the image.
