### ISSUE TITLE
Anyway to mount the files under a separate user?

### ISSUE THREAD

**Issue by jwheeler91** [spujadas/lighttpd-docker#5]
Anyway to mount the files under a separate user?

I mount this dirs:
/etc/lighttpd
/var/www/localhost/htdocs

But i like to specify a uid & gid

**Comment by spujadas** [comment]
Not quite sure what you're after, but generally speaking you will need to extend the image to alter file ownerships within the container.
Closing as this isn't an issue with the image, but here are some pointers you may find useful:
https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
https://www.berthon.eu/2018/containers-volumes-and-file-permissions/
http://www.inanzzz.com/index.php/post/q1rj/running-docker-container-with-a-non-root-user-and-fixing-shared-volume-permissions-with-dockerfile
