### ISSUE TITLE
Provide docker images with version tag

### ISSUE THREAD

**Issue by stefanneuhaus** [spujadas/lighttpd-docker#9]
The latest issue #8 broke our pipeline in production: as the docker images are only tagged with `latest` we always have to use the latest greatest.

The request is to have release versions and have the docker images tagged with these versions.

**Comment by spujadas** [comment]
Ah, didn't realise that the image was being used outside of sandbox environments.
The version of lighttpd is now pinned in the `Dockerfile` (f1bc14fa647d61f0994fb65efdb1ea3c68ef22d5), and releases and images are now tagged (current tag is `1.4.54-r0`).

There is still a caveat, as — as far as I understand — the Alpine Linux repo doesn't archive older packages versions for a given version of Alpine Linux, so manual builds of older images may fail once newer versions of lighttpd are released.

**Comment by stefanneuhaus** [comment]
Wow, that was lightning fast! ⚡️ 

I must admit that we do not actually use it in our production code but for integration testing. Thus it has the potential to block releases to production.

The caveat you mentioned is probably of no concern for all users who just _use_ the image. So this should be perfectly fine. Thanks again for the quick fix! 🎉

**Comment by spujadas** [comment]
Cheers!
